name: CI-CD-Pipeline-to-Server

on:
  push:
    branches: [ master ]
    
jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: actions/checkout@v1
      with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
    - name: Clone repository
      run: git clone git@github.com:cracit/sc.git
             
