name: CI-CD-Pipeline
env:
  DEPLOY_PATH: /tmp
  BUILD_SCRIPT_OUTPUT: dist

on:
  push:
    branches: [ master ]
    
jobs:
   build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup SSH Keys and known_hosts
                uses: appleboy/scp-action@master
                with:
                  host: ${{ secrets.DEPLOY_SERVER_HOST }}
                  username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
                  password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
                  source:  Migrate_server.sh
                  target: ${{ env.DEPLOY_PATH }}
                  strip_components: 1
