name: CI-CD-Pipeline
env:
  DEPLOY_PATH: /tmp
  BACKUP_PATH: /tmp/sc.backup

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          #port: ${{ secrets.PORT }}
          
          script: |
            cd $DEPLOY_PATH
            mv $DEPLOY_PATH /tmp/sc.backup/
            git clone git@github.com:cracit/sc.git
